pipeline {
    agent any
    stages {
        stage('Clean') {
            steps {
                dir('jenkins/pipeline') {
                    sh 'mvn clean'
                }
            }
        }
        stage('Test') {
            steps {
                dir('jenkins/pipeline'){
                    sh "mvn test"
                }
            }
        }
        stage('Package') {
            steps {
                dir('jenkins/pipeline') {
                    sh "mvn package"
                }
            }
        }
    }
}