pipeline {
    agent any
    stages {
        stage('Clone repository and Clean it') {
            steps {
                sh "cd jenkins/pipeline"
                sh "mvn clean"
            }
        }
        stage('Test') {
            steps {
                sh "mvn test"
            }
        }
        stage('Deploy') {
            steps {
                sh "mvn package"
            }
        }
    }
}